### ISSUE TITLE
pod install get an issue

### ISSUE THREAD

**Issue by w-i-n-s** [sgr-ksmt/FormToolbar#1]
//Cmd+C from readme and paste to Podfile, after - start "install"

pod install

[!] Invalid `Podfile` file: syntax error, unexpected '~', expecting keyword_end
    pod 'FormToolbar' ~> 1.0
                       ^.

 #  from /work/vusi/whitelabel_app/whitelabel/Podfile:17
 #  -------------------------------------------
 #      #pod 'IQKeyboardManager'
 >      pod 'FormToolbar' ~> 1.0
 #      
 #  -------------------------------------------

//Change to 'FormToolbar', '~> 1.0' 
pod install
Analyzing dependencies
[!] Unable to find a specification for `FormToolbar (~> 1.0)`

//Change to 'FormToolbar'
pod install
Analyzing dependencies
[!] Unable to find a specification for `FormToolbar`

**Comment by sgr-ksmt** [comment]
@w-i-n-s 
Sorry.. I wrote wrong line about `pod install`

Please try `pod 'FormToolbar', '~> 1.0'`. (REAME.md also updated just now.)
